### ISSUE TITLE
Problème avec pterodactyl

### ISSUE THREAD

**Issue by SpeedCode210** [TsWin/WebSite-Ping-API#1]
Lors de l’exécution sur pterodactyl, l'erreure suivante apparait lors d'un appel de l'api:
```
Error: ping.probe: there was an error while executing the ping program. . Check the path or permissions...
    at ChildProcess.<anonymous> (/home/container/node_modules/ping/lib/ping-promise.js:61:19)
    at Object.onceWrapper (events.js:421:26)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by TsWin** [comment]
@SpeedCode210

Cette issue ne sera pas corrigée car cela implique des services tiers.

**Comment by royaljacques** [comment]
est ce que  ce problème a été résolus ? car je l'ai aussi et aucune doc ne veux bien me dire pourquoi . c'est aussi sur ptéro

**Comment by TsWin** [comment]
Je vais essayer de la résoudre.
